<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<Version>4.1.0</Version>
	<Platforms>AnyCPU;x64</Platforms>
	<InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CoreOCRRuntime.Onnx.CPU.win-x64" Version="4.1.0" />
    <PackageReference Include="Scalar.AspNetCore.Microsoft" Version="2.14.14" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.8" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	<PackageReference Include="NLog" Version="5.2.8" />
	<PackageReference Include="NLog.Web.AspNetCore" Version="5.3.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreOCROnnx.SDK\CoreOCROnnx.SDK.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="StartOCRApi.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="StartOCRApi.sh">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
