<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <PackageId>CoreOCROnnx.SDK</PackageId>
	  <Version>4.1.0-beta01</Version>
	  <Authors>PaddleOCRCore</Authors>
	  <Company>PaddleOCRCore</Company>
	  <!-- NuGet Health Settings -->
	  <PublishRepositoryUrl>true</PublishRepositoryUrl>
	  <Deterministic>true</Deterministic>
	  <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
	<ItemGroup Condition="Exists('PaddleOCR')">
		<None Include="PaddleOCR\**\*">
			<Pack>true</Pack>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<PackagePath>build\PaddleOCR</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <Compile Remove="OCRModels\**" />
	  <EmbeddedResource Remove="OCRModels\**" />
	  <None Remove="OCRModels\**" />
	</ItemGroup>
</Project>
